### PR TITLE
Elements not found for scoped finders return usable CSS selectors

### LINKED ISSUE #24: Expected to find '.x / .y / .z' should not have slashes
This:
```
page.find('.x').find('.y').find('.z').shouldHave(...)
```
prints this when it fails to find:
```
Expected to find '.x / .y / .z'
```
...which is silly, because without the slashes, it's the right selector:
```
Expected to find '.x .y .z'
```

### PR DESCRIPTION
**Pull request by adiel**
Fixes #24

e.g.

expected to find: .outer .inner
expected to find: .outer:has(.inner)

### CODE REVIEW

File: test/assertionsSpec.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ describe('assertions', function(){
       return Promise.all([
         good1,
         good2,
-        expect(bad).to.be.rejected
+        expect(bad).to.be.rejected()
```
Comment (refractalize) [inline test/assertionsSpec.js]: I'm getting `TypeError: expect(...).to.be.rejected is not a function` on this... old chai perhaps?

**Comment by dereke** [comment]
thanks this is in 1.28.1
